// 图库数据：文物线索 + 素材收藏
// 正面 = 图片；背面 = 档案（双击图片翻面）
// 想改文案直接改这里的 name / era / source / state / note

const CLUES = [
  /* ===== 文物线索（做旧照片）===== */
  { id: 'r1', cat: 'relic', file: 'images/caiyou-vase.jpg', name: '霁蓝釉瓶', era: '明代 · 官窑', source: '守夜人 保存', state: '完好',
    note: '深蓝如天色。一窑只成一两件，烧它的人得等火候自己到位。它传了六百年，装过粮，也盛过水。' },
  { id: 'r2', cat: 'relic', file: 'images/footed-bowl.jpg', name: '青花高足碗', era: '明中期', source: '青瓷 保存', state: '完好',
    note: '碗足细高，缠枝莲纹。它不是被谁珍藏下来的，是没人当回事，才躲过一劫。' },
  { id: 'r3', cat: 'relic', file: 'images/jade-ruyi.jpg', name: '玉如意', era: '清', source: '如意 追回', state: '完好',
    note: '2014 年从老藏家家里被请走，2015 年出现在私下交易群里。有人跑了三趟，把它劝了回来。' },
  { id: 'r4', cat: 'relic', file: 'images/landscape.jpg', name: '水墨山水长卷', era: '清', source: '长卷 保存', state: '绢面起翘',
    note: '长卷怕潮。2016 年梅雨季，房间湿度到过 78%。恒温柜申请了三次，驳回了三次。' },
  { id: 'r5', cat: 'relic', file: 'images/plum.jpg', name: '梅花工笔画', era: '清中期 · 绢本', source: '过客 建档', state: '有霉斑',
    note: '一株梅花。有人给它建了档：每个月拍一次照，记下绢面的变化。' },
  { id: 'r6', cat: 'relic', file: 'images/doucai-plate.jpg', name: '斗彩大盘', era: '明宣德 · 斗彩', source: '陈列室', state: '2017-07-16 失窃',
    note: '柜子没有撬痕，钥匙人手一把，前一晚十点还有人签退。警方说：来源说不清，立案先缓缓。' },
  { id: 'r7', cat: 'relic', file: 'assets/old_photo2.jpg', name: '四人合影', era: '2016-12-28', source: '博物院门前', state: '手写批注',
    note: '第一次，也是唯一一次聚齐。右下角有人后来补写了一行字：2017.12.28。那天不是合影的日子，是站里最后还有人的一天。' },

  /* ===== 网页设计参考 ===== */
  { id: 'w01', cat: 'web', file: 'assets/clues/clue-01.jpg', name: '打字机与炭笔', era: '网页设计', source: '冰泡饭', state: '参考',
    note: '打字机等宽字配炭笔枯树，右侧竖排细字做导航。整页留白很多。' },
  { id: 'w02', cat: 'web', file: 'assets/clues/clue-02.jpg', name: '非遗站网格', era: '网页设计', source: '嗷呜', state: '参考',
    note: '标准商业网格：分区标题、四张门类卡、3×2 图文格。工整，也仅止于工整。' },
  { id: 'w03', cat: 'web', file: 'assets/clues/clue-03.jpg', name: '蓝色档案夹', era: '网页设计', source: 'OurYoungAndStupidYouth', state: '参考',
    note: '整站三段：星空封面、细线连起的拍立得阵列、最后落到一只档案夹——左页照片与证件卡，右页便利贴和批注。物证感最好的样本。' },
  { id: 'w04', cat: 'web', file: 'assets/clues/clue-04.jpg', name: '赞美懒惰', era: '网页设计', source: 'Lexiw!wi', state: '参考',
    note: '像素字、手写便签、打字机小字，三种字故意混在一起。角上有一个一直在走的时钟。' },
  { id: 'w05', cat: 'web', file: 'assets/clues/clue-05.jpg', name: '大漆与金箔', era: '底图', source: '爱取有', state: '可用',
    note: '靛蓝的大漆上撒了金箔，八个月相排成一道竖缝，底下压着一轮黑月。适合做整页开场。' },
  { id: 'w06', cat: 'web', file: 'assets/clues/clue-06.jpg', name: '青绿山水', era: '底图', source: '爱取有', state: '可用',
    note: '云海、山峦、一枚红日。纸的颗粒很细，铺满全屏也不吵。' },
  { id: 'w07', cat: 'web', file: 'assets/clues/clue-07.jpg', name: '绒花线框稿', era: '原型图', source: '西西', state: '参考',
    note: '灰阶线框，圆形序号配竖排小字，标题是中文大字压拼音。看的是骨架。' },
  { id: 'w08', cat: 'web', file: 'assets/clues/clue-08.jpg', name: '两座博物馆', era: '官网长图', source: '圈圈yes', state: '参考',
    note: '左朱红右墨绿，中间隔一条米白。文物都压在深色上，数据排成大字。' },
  { id: 'w09', cat: 'web', file: 'assets/clues/clue-09.jpg', name: '三重曝光', era: '底图', source: '春山怀刃', state: '可用',
    note: '同一个屋檐叠了三层影子，窗棂当了画框。褪色的粉与灰。' },
  { id: 'w10', cat: 'web', file: 'assets/clues/clue-10.jpg', name: '环形文字', era: '网页设计', source: '太阳雨', state: '参考',
    note: '文字绕成一扇空门，中间是名字和生卒年，底下三个细线圆按钮：想你了 389、说说话、送给你。整页只有一种颜色。' },
  { id: 'w11', cat: 'web', file: 'assets/clues/clue-11.jpg', name: '斜切取景', era: '海报', source: '友友家的猫', state: '参考',
    note: '黑色的斜切把画面裁开，缝里露出宫殿和两个背影。左上角是衬线英文大字。' },
  { id: 'w12', cat: 'web', file: 'assets/clues/clue-12.jpg', name: '幽蓝花与茶', era: '渲染图', source: '烛吉', state: '参考',
    note: '深蓝空间里的花、茶盏和发光的蝴蝶，物件都浮着。适合放在需要一点神秘感的局部。' },
  { id: 'w13', cat: 'web', file: 'assets/clues/clue-13.jpg', name: '细线标注', era: '展陈设计', source: '陈小瓜', state: '参考',
    note: '把鸟的每个部位用细线拉出来、标上名字。原来标注本身也可以很好看——我们的红线该学这个。' },
  { id: 'w14', cat: 'web', file: 'assets/clues/clue-14.jpg', name: '竹简秘境', era: '海报', source: 'DNA2725', state: '参考',
    note: '山水排成卷轴的形状，右端露出竹简。旁边一行打字机小字写着年份和名字。' },
  { id: 'w15', cat: 'web', file: 'assets/clues/clue-15.jpg', name: '观音垂泪', era: '拼贴海报', source: '###！', state: '参考',
    note: '红、黑、青三色硬碰硬，版式辅助线就那么露在外面。印章压在角上。' },
  { id: 'w16', cat: 'web', file: 'assets/clues/clue-16.jpg', name: '手绘边框', era: '网页设计', source: 'Dorispace', state: '参考',
    note: '手绘的抖动边框，宝丽来白框照片，标题是马克笔写的。' },

  /* ===== 古风底图 ===== */
  { id: 'g17', cat: 'guofeng', file: 'assets/clues/clue-17.jpg', name: '芥子 · 深褐藤叶', era: '底图', source: '彼彼彼岸花', state: '可用',
    note: '近黑的深褐，左上角一丛蓝色线描藤叶。右侧三分之二空着，正好留给字。' },
  { id: 'g18', cat: 'guofeng', file: 'assets/clues/clue-18.jpg', name: '芥子 · 玫红花枝', era: '底图 · 横', source: '彼彼彼岸花', state: '可用',
    note: '横构图，玫红底，白线勾花枝。像一张丝网印。饱和度很高，只宜做小面积或压暗使用。' },
  { id: 'g19', cat: 'guofeng', file: 'assets/clues/clue-19.jpg', name: '芥子 · 暗荷', era: '底图', source: '彼彼彼岸花', state: '可用',
    note: '暗绿底上的荷花，全靠细线勾形状。深色底子里最能压字的一张。' },
  { id: 'g20', cat: 'guofeng', file: 'assets/clues/clue-20.jpg', name: '芥子 · 园林', era: '底图', source: '彼彼彼岸花', state: '可用',
    note: '黑底白线画的园林：月洞门、挂落、栏杆、竹丛。线条很密，适合当章节封面，不适合垫字。' },
  { id: 'g21', cat: 'guofeng', file: 'assets/clues/clue-21.jpg', name: '米白与深绿', era: '版式范本', source: '茶茶与阿珍', state: '参考',
    note: '米白的纸底配深绿边纹，标题竖排。三栏，像一本合上的书。' },
  { id: 'g22', cat: 'guofeng', file: 'assets/clues/clue-22.jpg', name: '水彩与烫金', era: '插画', source: '舟舟的幻想世界', state: '可用',
    note: '淡彩水彩配金线，亭子和桃花挤在右上角。下面一大片干净，是给人写字的。' },
  { id: 'g23', cat: 'guofeng', file: 'assets/clues/clue-23.jpg', name: '飞鸟 · 赭红', era: '底素', source: '不知何名', state: '可用',
    note: '同版式的第一张。中央一个深色方框，天生就是放卡片的地方，飞鸟从左边穿出去。' },
  { id: 'g24', cat: 'guofeng', file: 'assets/clues/clue-24.jpg', name: '飞鸟 · 陶土', era: '底素', source: '不知何名', state: '可用',
    note: '赭红陶土色，粗麻布的颗粒。适合铜器、漆器这一类。' },
  { id: 'g25', cat: 'guofeng', file: 'assets/clues/clue-25.jpg', name: '飞鸟 · 豆青', era: '底素', source: '不知何名', state: '可用',
    note: '灰绿豆青，比赭红冷。适合玉器、青瓷。' },
  { id: 'g26', cat: 'guofeng', file: 'assets/clues/clue-26.jpg', name: '飞鸟 · 嫩绿', era: '底素', source: '不知何名', state: '可用',
    note: '三张里最亮的一张，明度高、干扰小，垫字最省力。' },
  { id: 'g27', cat: 'guofeng', file: 'assets/clues/clue-27.jpg', name: '误收的一张', era: '—', source: '—', state: '无关',
    note: '这张是新闻客户端的截图，与本档案无关，先留在这里备查。' },
  { id: 'g28', cat: 'guofeng', file: 'assets/clues/clue-28.jpg', name: '粉色垂帘', era: '免抠素材', source: '干脆面脑袋', state: '元素',
    note: '纱帘、窗格、风铃、流苏。可以拆开当装饰件，但整张太甜，不适合放在这里。' },
  { id: 'g29', cat: 'guofeng', file: 'assets/clues/clue-29.jpg', name: '石钵睡莲', era: '摄影', source: '此时情绪此时天', state: '可用',
    note: '俯拍的石板与石钵，睡莲是灰紫的。整张只有一个亮点，其余全是灰。' },
  { id: 'g30', cat: 'guofeng', file: 'assets/clues/clue-30.jpg', name: '雾中门楼', era: '摄影 · 横', source: '此时情绪此时天', state: '可用',
    note: '雾里的门楼，中央开着一扇窗——窗里那片白，是天然留给标题的地方。' },
  { id: 'g31', cat: 'guofeng', file: 'assets/clues/clue-31.jpg', name: '暗夜白莲', era: '摄影', source: '此时情绪此时天', state: '可用',
    note: '几乎全黑，只有一朵白睡莲亮着。白字压在任何位置都看得清。' },
  { id: 'g32', cat: 'guofeng', file: 'assets/clues/clue-32.jpg', name: '雾中荷池', era: '摄影 · 横', source: '此时情绪此时天', state: '可用',
    note: '前景残荷、中景白荷、远景是雾。三层，越远越淡。' },
  { id: 'g33', cat: 'guofeng', file: 'assets/clues/clue-33.jpg', name: '九宫格', era: '摄影合集', source: '此时情绪此时天', state: '参考',
    note: '一张门洞大图带着八张小图。大图放重点，小图放零碎，图录页可以照这个排。' },
  { id: 'g34', cat: 'guofeng', file: 'assets/clues/clue-34.jpg', name: '溪亭观涧', era: '水彩 · 长图', source: 'fuafua～', state: '可用',
    note: '水彩加烫金，亭子与桃花在左上，下面三分之二是干净的米白。' },
  { id: 'g35', cat: 'guofeng', file: 'assets/clues/clue-35.jpg', name: '折扇', era: '摄影', source: 'itsrainie', state: '可用',
    note: '半透的扇面后头是虚掉的花。扇骨排得很匀，像一把尺。' },
  { id: 'g36', cat: 'guofeng', file: 'assets/clues/clue-36.jpg', name: '睡莲微距', era: '摄影', source: 'itsrainie', state: '可用',
    note: '顶光很硬，花白得发亮，水压到近黑。花与叶把画面填满了。' },
  { id: 'g37', cat: 'guofeng', file: 'assets/clues/clue-37.jpg', name: '水下的伞', era: '摄影 · 横', source: 'itsrainie', state: '可用',
    note: '伞沉在水下，只剩伞面亮着。水面把一切都揉皱了。' },
  { id: 'g38', cat: 'guofeng', file: 'assets/clues/clue-38.jpg', name: '佛首与花', era: '摄影 · 横', source: 'itsrainie', state: '可用',
    note: '白佛首在左，一朵重瓣花在右，背景压得很暗。' },
  { id: 'g39', cat: 'guofeng', file: 'assets/clues/clue-39.jpg', name: '木案清供', era: '摄影 · 横', source: 'itsrainie', state: '可用',
    note: '暗木桌面上一枝荷花，洒了几片花瓣。信息量很少，压字正好。' },
  { id: 'g40', cat: 'guofeng', file: 'assets/clues/clue-40.jpg', name: '一组青瓷', era: '摄影 · 横', source: 'itsrainie', state: '可用',
    note: '青瓷盖碗配一朵粉荷，是标准的器物特写。粉青这个颜色可以取出来当主色。' },
  { id: 'g41', cat: 'guofeng', file: 'assets/clues/clue-41.jpg', name: '重影莲花', era: '摄影', source: 'itsrainie', state: '可用',
    note: '两张叠在一起的花，前景虚，背景透出窗格和人影。像一张褪色的旧照。' },
  { id: 'g42', cat: 'guofeng', file: 'assets/clues/clue-42.jpg', name: '仰视伞骨', era: '摄影 · 小图', source: 'itsrainie', state: '小尺寸',
    note: '从下往上看一把撑开的伞，放射状的伞骨。图不大，只适合放小尺寸。' },
  { id: 'g43', cat: 'guofeng', file: 'assets/clues/clue-43.jpg', name: '白玉兰', era: '摄影 · 方', source: '芝士小狗', state: '可用',
    note: '黑窗框把白玉兰和白墙框在中间。几乎是单色的，只剩一点暖灰。' },
  { id: 'g44', cat: 'guofeng', file: 'assets/clues/clue-44.jpg', name: '山隐飞鸟', era: '三宫格', source: '张海子', state: '参考',
    note: '三格：竹枝、一行飞鸟的天空、三层远山。可以拆开单用。' },

  /* ===== 配色 ===== */
  { id: 'c45', cat: 'color', file: 'assets/clues/clue-45.jpg', name: '六格夜景', era: '红蓝', source: '兔叽只', state: '参考',
    note: '深蓝的夜里全是发烫的红：霓虹、车尾灯、一条金鱼、一朵蓝底的花。' },
  { id: 'c46', cat: 'color', file: 'assets/clues/clue-46.jpg', name: '克莱因蓝与牡丹', era: '红蓝', source: '宵夜', state: '参考',
    note: '整片克莱因蓝，贴上大红牡丹和蝴蝶。画面正中，两只手之间有一根红线连着。' },
  { id: 'c47', cat: 'color', file: 'assets/clues/clue-47.jpg', name: '劲爽蓝与激爽红', era: '红蓝 · 色值', source: 'DENGubai', state: '取色',
    note: '蓝 #0057B8，红 #FF0033。两个字，一正一反，就这一件事。' },
  { id: 'c48', cat: 'color', file: 'assets/clues/clue-48.jpg', name: '红蓝配比', era: '红蓝 · 色值', source: '多丽思美学研究院', state: '取色',
    note: '五组红蓝搭配，右下角写着比例：40 比 40 比 20。我们的序章那条横线就是照这个画的。' },
  { id: 'c49', cat: 'color', file: 'assets/clues/clue-49.jpg', name: '日常尺度', era: '红蓝 · 应用', source: '色卡织造局', state: '取色',
    note: '浅蓝、米白、深红。这是不刺眼的红蓝，可以放到生活里。' },
  { id: 'c50', cat: 'color', file: 'assets/clues/clue-50.jpg', name: '国风 · 藏蓝紫', era: '国风配色', source: '叮丁町叮叮', state: '备用',
    note: '深藏蓝紫 #33375C，米灰 #CCBBA9，赭橙 #C96E3F。留给古风版。' },
  { id: 'c51', cat: 'color', file: 'assets/clues/clue-51.jpg', name: '国风 · 其四', era: '国风配色', source: '叮丁町叮叮', state: '备用', note: '国风组第四张，做古风版时再定色。' },
  { id: 'c52', cat: 'color', file: 'assets/clues/clue-52.jpg', name: '国风 · 其五', era: '国风配色', source: '叮丁町叮叮', state: '备用', note: '国风组第五张，做古风版时再定色。' },
  { id: 'c53', cat: 'color', file: 'assets/clues/clue-53.jpg', name: '国风 · 其六', era: '国风配色', source: '叮丁町叮叮', state: '备用', note: '国风组第六张，做古风版时再定色。' },
  { id: 'c54', cat: 'color', file: 'assets/clues/clue-54.jpg', name: '国风 · 其九', era: '国风配色', source: '叮丁町叮叮', state: '备用', note: '国风组第九张，做古风版时再定色。' },
];

const CATS = [
  { key: 'all',     label: '全部' },
  { key: 'relic',   label: '文物线索' },
  { key: 'web',     label: '网页设计' },
  { key: 'guofeng', label: '古风底图' },
  { key: 'color',   label: '配色样本' },
];

window.CLUES = CLUES;
window.CATS = CATS;
